# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 223)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setGeometry(QtCore.QRect(10, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DownloadButton.setFont(font)
        self.DownloadButton.setObjectName("DownloadButton")
        self.convertBox = QtWidgets.QGroupBox(self.centralwidget)
        self.convertBox.setGeometry(QtCore.QRect(0, 70, 281, 91))
        self.convertBox.setObjectName("convertBox")
        self.radioButtonWav = QtWidgets.QRadioButton(self.convertBox)
        self.radioButtonWav.setGeometry(QtCore.QRect(10, 40, 80, 16))
        self.radioButtonWav.setObjectName("radioButtonWav")
        self.radioButtonMp3 = QtWidgets.QRadioButton(self.convertBox)
        self.radioButtonMp3.setGeometry(QtCore.QRect(10, 60, 166, 16))
        self.radioButtonMp3.setObjectName("radioButtonMp3")
        self.radioButtonMp4 = QtWidgets.QRadioButton(self.convertBox)
        self.radioButtonMp4.setGeometry(QtCore.QRect(10, 20, 166, 16))
        self.radioButtonMp4.setObjectName("radioButtonMp4")
        self.ytlinksBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ytlinksBox.setGeometry(QtCore.QRect(0, 10, 311, 51))
        self.ytlinksBox.setObjectName("ytlinksBox")
        self.YoutubeLinkLineEdit = QtWidgets.QLineEdit(self.ytlinksBox)
        self.YoutubeLinkLineEdit.setGeometry(QtCore.QRect(10, 20, 291, 20))
        self.YoutubeLinkLineEdit.setObjectName("YoutubeLinkLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Downloader"))
        self.DownloadButton.setText(_translate("MainWindow", "Download"))
        self.convertBox.setTitle(_translate("MainWindow", "Conver to:"))
        self.radioButtonWav.setText(_translate("MainWindow", ".wav(Audio)"))
        self.radioButtonMp3.setText(_translate("MainWindow", ".mp3(audio)"))
        self.radioButtonMp4.setText(_translate("MainWindow", ".mp4(Video)"))
        self.ytlinksBox.setTitle(_translate("MainWindow", "YouTube Link"))
